# Generated by Django 4.1.7 on 2023-03-29 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_rename_user_author_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='username',
            new_name='user',
        ),
    ]
